### ISSUE TITLE
cuDNN and tf versions

### ISSUE THREAD

**Issue by tonytaylor85** [lbfs/DeepFaceLab_Linux#11]
I had a working install on Mint 19.1 with a GTX1660ti.  I decided to try and add GPU DLIB support but now I think I have version conflicts with cuDNN and tensorflow.  I've just done a fresh install of ubuntu 16.04 to experiment with a clean environment. I used the install script but i get the same errors i was getting on my mint install.

cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

I've mixed and matched versions with no success.  What's the current working combination?

**Comment by lbfs** [comment]
You have a new GPU so you need to use CUDA 10.0 and TF 1.13
 
requirements.txt
```python
numpy==1.16.1
pathlib==1.0.1
scandir==1.6
h5py==2.7.1
Keras==2.2.4
opencv-python==4.0.0.21
tensorflow-gpu==1.13.1
plaidml-keras==0.5.0
scikit-image
dlib==19.16.0
tqdm
git+https://www.github.com/keras-team/keras-contrib.git
```

Ubuntu 16.04
```bash
# Add NVIDIA package repositories
# Add HTTPS support for apt-key
sudo apt-get install gnupg-curl
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo apt-get update
wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb
sudo apt install ./nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb
sudo apt-get update

# Install NVIDIA Driver
# Issue with driver install requires creating /usr/lib/nvidia
sudo mkdir /usr/lib/nvidia
sudo apt-get install --no-install-recommends nvidia-410
# Reboot. Check that GPUs are visible using the command: nvidia-smi

# Install development and runtime libraries (~4GB)
sudo apt-get install --no-install-recommends \
    cuda-10-0 \
    libcudnn7=7.4.1.5-1+cuda10.0  \
    libcudnn7-dev=7.4.1.5-1+cuda10.0
```

Try this, I have no idea if it works.

**Comment by lbfs** [comment]
All of this makes sense to me because this used to be the older style installation, but why did you change the final part in the code?

Did it prevent you from running? Anyways, your model might be unstable later on in training due to memory problems, if you're already getting that at start.

**Comment by lbfs** [comment]
Also I recommend trying an optimization mode of 3, that might solve your problems as well, but I can't make any guarantees.

**Comment by tonytaylor85** [comment]
with allow_growth=True it runs but with OOM errors.
allow_growth=False I get this, basically the same no matter which model I use.

`===== Model summary =====
== Model name: LIAEF128
==
== Current iteration: 2818
==
== Model options:
== |== batch_size : 6
== |== sort_by_yaw : False
== |== random_flip : True
== |== pixel_loss : False
== |== write_preview_history : True
== Running on:
== |== [0 : GeForce GTX 1660 Ti]
=========================
Starting. Press "Enter" to stop training and save model.
WARNING:tensorflow:From /home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-03-22 13:22:50.720491: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-03-22 13:22:50.722066: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-03-22 13:22:50.729725: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-03-22 13:22:50.730944: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-03-22 13:22:50.732146: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-03-22 13:22:50.733347: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-03-22 13:22:50.744040: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-22 13:22:50.746071: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Error: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node model_1/conv2d_1/convolution}}]]
	 [[{{node loss/model_2_loss_1/Mean_3}}]]
Traceback (most recent call last):
  File "/home/owner/DeepFaceLab_Linux/mainscripts/Trainer.py", line 78, in trainerThread
    loss_string = model.train_one_iter()
  File "/home/owner/DeepFaceLab_Linux/models/ModelBase.py", line 362, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "/home/owner/DeepFaceLab_Linux/models/Model_LIAEF128/Model.py", line 77, in onTrainOneIter
    loss_src = self.autoencoder_src.train_on_batch( [warped_src, target_src_mask], [target_src, target_src_mask] )
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node model_1/conv2d_1/convolution}}]]
	 [[{{node loss/model_2_loss_1/Mean_3}}]]
Done.
`

Should I try config.gpu_options.per_process_gpu_memory_fraction?  I'm new to GPGPU and deep learning but I'm glad to help.
I'll note that my virgin test install of ubuntu 16.04 gave the same results.
SAE model @128 and opt 3 did give two early OOM but no more yet.

**Comment by lbfs** [comment]
What video driver?

**Comment by tonytaylor85** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 166...  Off  | 00000000:1C:00.0  On |                  N/A |
| 33%   37C    P0    26W / 130W |    224MiB /  5913MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2760      G   /usr/lib/xorg/Xorg                           198MiB |
|    0      2990      G   xfwm4                                          2MiB |
|    0     21504      G   ...quest-channel-token=4494128409599907215    21MiB |
+-----------------------------------------------------------------------------+

**Comment by lbfs** [comment]
Hmm, you should have enough vram, I'll take a look at this tonight and see if I can get something to work.

**Comment by tonytaylor85** [comment]
cudnn-10.0-linux-x64-v7.4.2.24

and i still get 
`2019-03-22 13:46:40.600464: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 293.34M (307589888 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 13:46:43.045948: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 293.34M (307589888 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 13:46:50.409043: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 293.34M (307589888 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
`

**Comment by tonytaylor85** [comment]
It starts larger
`Starting. Press "Enter" to stop training and save model.
WARNING:tensorflow:From /home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-03-22 13:45:45.123536: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.06G (1135017984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 13:45:45.124305: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 974.19M (1021516288 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 13:45:45.124955: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 876.77M (919364608 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 13:46:01.576501: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 293.34M (307589888 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 13:46:01.577175: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 293.34M (307589888 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
`

**Comment by lbfs** [comment]
Is this still with LIAEF128 and a batch size of 6?

**Comment by tonytaylor85** [comment]
yes, LIAEF128 and batch size 6.  I'd clipped that part cause it was parsed as markdown i think.
LIAEF also goes OOM at batch size of 2.
H64 gives OOM at batch sizes larger than 13.  Under that it is fine.

`Model summary
Model name: LIAEF128
Current iteration: 3543
Model options:
batch_size : 2
sort_by_yaw : False
random_flip : True
pixel_loss : False
write_preview_history : True
Running on: [0 : GeForce GTX 1660 Ti]

Starting. Press "Enter" to stop training and save model.
WARNING:tensorflow:From /home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-03-22 13:55:36.310480: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.09G (1168572416 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 13:55:36.311325: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1002.99M (1051715328 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 13:55:36.312160: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 902.69M (946543872 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 13:55:56.631768: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 302.01M (316682752 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
`

**Comment by lbfs** [comment]
```
numpy==1.16.1
h5py==2.9.0
Keras==2.2.4
opencv-python==4.0.0.21
https://github.com/evdcush/TensorFlow-wheels/releases/download/tf-1.12.0-gpu-10.0/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl ; sys_platform == "linux"
plaidml-keras==0.5.0
scikit-image
tqdm
ffmpeg-python==0.1.17
git+https://www.github.com/keras-team/keras-contrib.git
```
@tonytaylor85 try downgrading tf from 1.13 to 1.12, there was a performance regression in tf1.13 noticed on mainstream builds, here is the updated requirements.txt

**Comment by tonytaylor85** [comment]
LIAEF 128 batch 6, very slow to start.

`2019-03-22 16:18:22.751777: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 368.43M (386327552 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 16:18:22.753877: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 368.43M (386327552 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 16:18:22.754732: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 368.43M (386327552 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory`
Lots and lots of these
`2019-03-22 16:18:22.757384: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 368.43M (386327552 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-22 16:18:22.758230: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 368.43M (386327552 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Error: OOM when allocating tensor with shape[6,128,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node training_1/Adam/gradients/model_2_1/conv2d_8/convolution_grad/Conv2DBackpropInput}} = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@train...propFilter"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training_1/Adam/gradients/model_2_1/conv2d_8/convolution_grad/Conv2DBackpropInput-0-VecPermuteNHWCToNCHW-LayoutOptimizer, conv2d_8/kernel/read, training_1/Adam/gradients/model_2_1/conv2d_8/Sigmoid_grad/SigmoidGrad)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "/home/owner/DeepFaceLab_Linux/mainscripts/Trainer.py", line 78, in trainerThread
    loss_string = model.train_one_iter()
  File "/home/owner/DeepFaceLab_Linux/models/ModelBase.py", line 362, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "/home/owner/DeepFaceLab_Linux/models/Model_LIAEF128/Model.py", line 78, in onTrainOneIter
    loss_dst = self.autoencoder_dst.train_on_batch( [warped_dst, target_dst_mask], [target_dst, target_dst_mask] )
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/owner/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[6,128,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node training_1/Adam/gradients/model_2_1/conv2d_8/convolution_grad/Conv2DBackpropInput}} = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@train...propFilter"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training_1/Adam/gradients/model_2_1/conv2d_8/convolution_grad/Conv2DBackpropInput-0-VecPermuteNHWCToNCHW-LayoutOptimizer, conv2d_8/kernel/read, training_1/Adam/gradients/model_2_1/conv2d_8/Sigmoid_grad/SigmoidGrad)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Done.
`

**Comment by lbfs** [comment]
Can't really help without the hardware to replicate this, most I can say is try to follow suggestions or debug on own. Sorry.
