### ISSUE TITLE
issue with Tensorflow and cudnn

### ISSUE THREAD

**Issue by sanych10** [lbfs/DeepFaceLab_Linux#12]
Greetings.  following error appears when training SAE. Tried updating tensorflow to 1.13 training proceeds but errors for collocation of TF appears but training goes on AND seems to use CPU.
Below is original error. No training possible in the original scenario.  System Ubuntu 18.10 CPU i97980xe. NVIDIA Titan V.

Starting. Press "Enter" to stop training and save model.
2019-03-24 11:21:34.768749: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.770822: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.780155: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.785224: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.795342: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.801473: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.811039: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.817293: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.826713: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.832314: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.841769: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.848019: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.857455: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.862833: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.872208: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-24 11:21:34.878074: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Error: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node convolution_3}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](convolution_3-0-TransposeNHWCToNCHW-LayoutOptimizer, Const_3)]]
	 [[{{node add_66/_721}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4659_add_66", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Traceback (most recent call last):
  File "/media/alex/AI/DeepFaceLab_Linux/mainscripts/Trainer.py", line 78, in trainerThread
    loss_string = model.train_one_iter()
  File "/media/alex/AI/DeepFaceLab_Linux/models/ModelBase.py", line 362, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "/media/alex/AI/DeepFaceLab_Linux/models/Model_SAE/Model.py", line 430, in onTrainOneIter
    src_loss, dst_loss, = self.src_dst_train (feed)
  File "/home/alex/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/alex/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/alex/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/alex/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node convolution_3}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](convolution_3-0-TransposeNHWCToNCHW-LayoutOptimizer, Const_3)]]
	 [[{{node add_66/_721}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4659_add_66", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Done.

**Comment by lbfs** [comment]
How did you install?

**Comment by lbfs** [comment]
If you're on Ubuntu 18.10, have you tried rebooting? I get this every once in a while.

**Comment by sanych10** [comment]
installed using your script.

**Comment by sanych10** [comment]
then manually installed tensorflow 1.13 and training initiated but only using cpu. I guess due to collocation error

**Comment by lbfs** [comment]
You could try the LXD install instructions, I'm using those without issue currently on Ubuntu 18.10. I have a feeling something might be messed up with Anaconda3 installation instructions and I need to look into it.

**Comment by lbfs** [comment]
By chance have you used plaidML on your system? Sometimes that can cause this error to occur.

**Comment by sanych10** [comment]
I will try LXD. will report back

**Comment by sanych10** [comment]
> I will try LXD. will report back
p.s. no plaidml

**Comment by lbfs** [comment]
``lxc config device add deepfacelab shared disk path=/mnt/secondary source=/mnt/secondary``
also since you have multiple storage like me, you may need to add access to it into your container, you can do it with this command

**Comment by sanych10** [comment]
this after executing instructions?

**Comment by lbfs** [comment]
oh before ``lxc exec deepfacelab -- su ubuntu``

**Comment by lbfs** [comment]
you can technically add it after as long as your not in the container.

**Comment by sanych10** [comment]
ok not too late :)

**Comment by sanych10** [comment]
input: lxc config device add deepfacelab shared disk path=/media/alex/AI/
output:Error: Invalid devices: Disk entry is missing the required "source" property

**Comment by lbfs** [comment]
``lxc config device add deepfacelab shared disk path=/media/alex/AI/ source=/media/alex/AI/```

**Comment by sanych10** [comment]
yes! for this bit

**Comment by sanych10** [comment]
after ubuntu script do I need to execute rest of Ubuntu 18.04 instructions:
"wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo apt-get update"

**Comment by lbfs** [comment]
no

**Comment by lbfs** [comment]
as long as video driver matches one inside the container then all is good

**Comment by sanych10** [comment]
still executing the script... seems like pulling new ubuntu distro inside :)

**Comment by lbfs** [comment]
anyways, i have to go, 

if you have issues try ``no_preview`` scripts first with write preview history on and see if it works correctly

and two, you may need to play around with video drivers inside container and host to get them to match perfectly.

I recommend this ppa https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by sanych10** [comment]
got it thanks. will report if regardless of outcome :)
