### ISSUE TITLE
win10 is work

### ISSUE THREAD

**Issue by oracle9i88** [lbfs/DeepFaceLab_Linux#4]
Using TensorFlow backend.
Loading: 0it [00:00, ?it/s]
Loading: 100%|#################################| 19/19 [00:00<00:00, 512.79it/s]
Error: integer division or modulo by zero
Traceback (most recent call last):
  File "/root/DeepFaceLab_Linux/mainscripts/Trainer.py", line 41, in trainerThread
    device_args=device_args)
  File "/root/DeepFaceLab_Linux/models/ModelBase.py", line 154, in __init__
    self.sample_for_preview = self.generate_next_sample()
  File "/root/DeepFaceLab_Linux/models/ModelBase.py", line 306, in generate_next_sample
    return [next(generator) for generator in self.generator_list]
  File "/root/DeepFaceLab_Linux/models/ModelBase.py", line 306, in <listcomp>
    return [next(generator) for generator in self.generator_list]
  File "/root/DeepFaceLab_Linux/samples/SampleGeneratorFace.py", line 57, in __next__
    generator = self.generators[self.generator_counter % len(self.generators) ]
ZeroDivisionError: integer division or modulo by zero
Done.

**Comment by oracle9i88** [comment]
ubuntu16.04，Tesla p4

**Comment by oracle9i88** [comment]
cuda9.0  cudnn 7.1.4

**Comment by lbfs** [comment]
You need to have images in your data_dst or data_src directory for this to work.
